---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0  # Use the ref you want to point at
    hooks:
      - id: check-yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.3
    hooks:
      - id: shellcheck
        name: Check shell scripts with shellcheck
        exclude_types: [zsh]
        args: []
  - repo: local
    hooks:
      - id: check-urls
        name: Check URLs exist and are valid
        language: python
        language_version: python2.7
        entry: .travis/tests.py
        types: [salt]
        additional_dependencies: [pyaml, jinja2, pycurl, gitpython]
