---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
repos:
  - repo: local
    hooks:
      - id: check-urls
        name: Check URLs exist and are valid
        language: python
        language_version: python2.7
        entry: .travis/tests.py
        types: [salt]
        additional_dependencies: [pyaml, jinja2, pycurl, gitpython]
