language: python
cache:
    pip: true
    directories:
        - $HOME/.cache/pre-commit
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libcurl4-openssl-dev
install: pip install pre-commit
script: |
  echo $TRAVIS_COMMIT_RANGE
  if [ -z "${TRAVIS_COMMIT_RANGE}" ] ; then
      # This is a new branch.
      echo "Nothing to do"
  else
      # This isn't a new branch.
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ] ; then
          # This isn't a PR build.
  
          # We need the individual commits to detect force pushes.
          COMMIT1="$(echo ${TRAVIS_COMMIT_RANGE} | cut -f 1 -d '.')"
          COMMIT2="$(echo ${TRAVIS_COMMIT_RANGE} | cut -f 4 -d '.')"
          echo ${COMMIT1}
          echo ${COMMIT2}
  
          if [ "$(git cat-file -t ${COMMIT1} 2>/dev/null)" = commit -a "$(git cat-file -t ${COMMIT2} 2>/dev/null)" = commit ] ; then
              # This is a 'normal' build.
              echo "Checking commits:"
              git log --format=oneline --abbrev-commit ${COMMIT1}..${COMMIT2}
              git diff --name-only ${COMMIT1}..${COMMIT2} --
              pre-commit run --from-ref ${COMMIT1} --to-ref ${COMMIT2}
          else
              # This was a history rewrite.
              echo "Not sure what to do"
          fi
      else
          # This is a PR build.
          echo "Checking commits:"
          git log --format=oneline --abbrev-commit ${TRAVIS_BRANCH}..HEAD
          git diff --name-only ${TRAVIS_BRANCH}..HEAD --
          pre-commit run --from-ref ${TRAVIS_BRANCH} --to-ref HEAD
      fi
  fi
