name: full_run_win

on:
  workflow_call:
  # Allow manual trigger
  workflow_dispatch:
  schedule:
    # At 17:03 on Saturday (on main SaltStack repo)
    - cron: '3 17 * * 6'

jobs:
  gsv:
    name: Get Salt versions
    if: github.event_name == 'workflow_dispatch' || !github.event.repository.fork
    runs-on: ubuntu-latest
    outputs:
      salt-latest: ${{ steps.get-salt-versions.outputs.salt-latest }}
    steps:
      - id: get-salt-versions
        uses: dafyddj/get-salt-versions@v2
  test:
    name: Run URL tests
    needs: gsv
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Salt
        uses: dafyddj/setup-salt-win@v2
        with:
          salt-version: ${{ needs.gsv.outputs.salt-latest }}
      - name: Setup `pip` dependencies
        run: |
          salt-pip install python-magic-bin tabulate
          if ($LASTEXITCODE) {
              Write-Host ("::error title=salt-pip::salt-pip returned exit code: $LASTEXITCODE")
              exit 1
          }
      - name: Run URL test
        run: |
          & "C:\Program Files\Salt Project\Salt\Scripts\python.exe" .\.cicd\tests.py --cron
