name: Test on Windows

on:
  - pull_request
  - push
  - workflow_call
  - workflow_dispatch

jobs:
  gsv:
    name: Get Salt versions
    runs-on: ubuntu-latest
    outputs:
      salt-latest: ${{ steps.get-salt-versions.outputs.salt-latest }}
    steps:
      - id: get-salt-versions
        uses: dafyddj/get-salt-versions@1fcbea0eee4404137e534d66f3c22846f7c2a7ec # v3.0.0
  test:
    name: Run URL tests
    needs: gsv
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - id: changed-files
        name: Get changed files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          list-files: json
          filters: |
            sls:
              - added|modified:
                - '**/*.sls'
      - name: Setup Salt
        if: steps.changed-files.outputs.sls == 'true'
        uses: dafyddj/setup-salt-win@1fe09b1c0cdb721a43f9e5faa9bd079af8701803 # v2.2.0
        with:
          salt-version: ${{ needs.gsv.outputs.salt-latest }}
      - name: Setup `pip` dependencies
        if: steps.changed-files.outputs.sls == 'true'
        run: |
          salt-pip install python-magic-bin tabulate
          if ($LASTEXITCODE) {
              Write-Host ("::error title=salt-pip::salt-pip returned exit code: $LASTEXITCODE")
              exit 1
          }
      - name: Run URL test
        if: steps.changed-files.outputs.sls == 'true'
        run: |
          & "C:\Program Files\Salt Project\Salt\Scripts\python.exe" .\.cicd\tests.py ${{ join(fromJSON(steps.changed-files.outputs.sls_files), ' ') }}
