name: Pre-Commit

on:
  - pull_request
  - push
  - workflow_call
  - workflow_dispatch

jobs:
  Pre-Commit:
    name: Run Pre-Commit

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: .cicd/pre-commit.txt
    - name: Run Pre-Commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
