name: Pre-Commit

on:
  - pull_request
  - push
  - workflow_call
  - workflow_dispatch

jobs:
  Pre-Commit:
    name: Run Pre-Commit

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: .cicd/pre-commit.txt
    - name: Run Pre-Commit
      uses: pre-commit/action@v3.0.0
