name: Test `pkg.refresh_db`

on:
  - pull_request
  - push
  - workflow_call
  - workflow_dispatch

jobs:
  gsv:
    name: Get Salt versions
    runs-on: ubuntu-latest
    outputs:
      salt-versions-els: ${{ steps.get-salt-versions.outputs.salt-versions-els }}
      salt-versions: ${{ steps.get-salt-versions.outputs.salt-versions }}
    steps:
      - id: get-salt-versions
        uses: dafyddj/get-salt-versions@1fcbea0eee4404137e534d66f3c22846f7c2a7ec # v3.0.0
  test:
    name: Test `pkg.refresh_db`
    needs: gsv
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        salt-version:
          - ${{ fromJSON(needs.gsv.outputs.salt-versions-els) }}
          - ${{ fromJSON(needs.gsv.outputs.salt-versions) }}
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: win/repo-ng
      - name: Setup Salt
        uses: dafyddj/setup-salt-win@f40127f4980d09e8c6bf82759dd29e97b17e3356 # v2.1.1
        with:
          salt-version: ${{ matrix.salt-version }}
          custom-config: |
            osenv:
              driver: env
            file_roots:
              base:
                - sdb://osenv/GITHUB_WORKSPACE
      - name: Run `salt-call pkg.refresh_db`
        run: |
          $pkgs = (salt-call --out=json pkg.refresh_db | ConvertFrom-Json).local
          if ($LASTEXITCODE) {
              Write-Host ("::error title=salt-call::salt-call returned exit code: $LASTEXITCODE")
              exit 1
          }
          $pkgs
  results:
    name: Collect results
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests succeeded!"
