name: schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  pre-commit:
    name: Check URLs
    if: github.repository == 'dafyddj/salt-winrepo-ng' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: |
          sudo apt update
          sudo apt install -y libcurl4-openssl-dev
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --verbose --all-files
